version: 2
updates:
# Update packages
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
    - dependency-name: "dbots"
  commit-message:
    prefix: chore
    include: scope
# Update locale submodule
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  target-branch: dev
  commit-message:
    prefix: chore
    include: scope
  labels:
    - "dependabot-submodules"
